/* 
 * Represents the car as a whole, controlling the various subsystems
 * PLEASE DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
 * 
 * 
 * Author: Matthew Larson
 */

#include <iostream>
#include <time.h>
#include "car.h"


// I'm not sure why I need this preprocessor, but this works...
// https://stackoverflow.com/questions/68742519/why-cant-i-use-the-nanosleep-function-even-when-time-h-is-includedhttps://stackoverflow.com/questions/68742519/why-cant-i-use-the-nanosleep-function-even-when-time-h-is-included
#define _POSIX_C_SOURCE 199309L


Car::Car(){
    // All of the subsystems constructor's are alreading being called. So only 
    // Write code relevant to the car here.

    init();
    execute();
}

Car::~Car(){
    end();
}

void Car::execute(){
    // ! WARNNING: not tested on raspberry pi. 
    // ! Does not work with frequency 1 for whatever reason...
    int frequency = 200;   // CAN can go up to 1 Mhz or 1000000 hz

    float cycleTime = 1.0 / frequency;  // Length of time to sleep
    int cycleTimens = (int)(cycleTime * 1000000000L);

    int i = 0;

    // I'm not exactly sure if this is exactly what we want, but it "should" be good enough for now

    while(1){
        // req defines a time value required by nanosleep 
        struct timespec req = {0};
        req.tv_sec = 0;
        req.tv_nsec = cycleTimens;
        nanosleep(&req, (struct timespec *)NULL);


    }

    // printing for other subsystems only works if you print something to the terminal...?
    std::cout << "";
}

void Car::init(){
    std::cout << "Car Sucessfully Initialized\n";
}

void Car::end(){
    std::cout << "Car sucessfully destroyed\n";
}